### ISSUE TITLE
Support PEP 440 local version identifiers

### ISSUE THREAD

**Issue by brainsik** [royw/Versio#1]
Parsing a string with a local version identifier results in an AttributeError. As an example, try "1.0+abc.5" which is in the PEP 440 doc.

https://www.python.org/dev/peps/pep-0440/#local-version-identifiers

**Comment by royw** [comment]
Thank you!
Just pushed 0.2.0 to github.  Added PEP440 local version identifier support.  Please examine the unit tests to see if I'm covering locals well enough.

**Comment by brainsik** [comment]
Thanks for adding support, @royw.
