### ISSUE TITLE
Publish wheels to pypi?

### ISSUE THREAD

**Issue by matthewdeanmartin** [royw/Versio#8]
I can't tell if you use this [herringfile](https://github.com/royw/Versio/blob/36d2c36e6667e7422c79c5661a6ea728406817b2/herringfile) to publish to pypi --
But that build script supports wheels, but I [can't find the wheels in pypi](https://pypi.org/project/Versio/#files).

If you could add bdist_wheel as well as sdist that would be a huge help to folk who for policy reasons would like to only install wheels.

Here are some more [instructions on how to create wheels](https://www.realpythonproject.com/how-to-create-a-wheel-file-for-your-python-package-and-import-it-in-another-project/), or you could use poetry build which is even easier once you've started using poetry.

Thanks for publishing Versio, it was handy for parsing version numbers in my own side project [jiggle_version](https://github.com/matthewdeanmartin/jiggle_version)

**Comment by royw** [comment]
It looks like wheel usage has changed over the years (back then I just thought it was for binary distributions).  Would a --universal wheel work?  I'll investigate pushing the wheel this evening.

Thank you

**Comment by royw** [comment]
Should have wheels for Versio-0.5.0 on pypi.org.  Enjoy!
P.S. jiggle_version is interesting!
